name: CI Workflow (Debug Version)

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  CI: true

jobs:
  debug-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Debug - List files
      run: |
        echo "=== Repository contents ==="
        ls -la
        echo "=== Package.json exists? ==="
        test -f package.json && echo "✓ package.json found" || echo "✗ package.json missing"
        
    - name: Debug - Show package.json scripts
      run: |
        echo "=== Available npm scripts ==="
        npm run 2>/dev/null || echo "No scripts available"
        
    - name: Install dependencies
      run: |
        echo "=== Installing dependencies ==="
        npm ci --legacy-peer-deps
        echo "=== Installation complete ==="
        
    - name: Check if lint script exists
      run: |
        if npm run | grep -q "lint"; then
          echo "Lint script found"
          npm run lint
        else
          echo "No lint script found, skipping..."
        fi
      continue-on-error: true
      
    - name: Run tests with coverage
      run: |
        if npm run | grep -q "test"; then
          npm test -- --coverage --ci --watchAll=false --passWithNoTests
        else
          echo "No test script found, skipping tests..."
        fi
      continue-on-error: true
      
    - name: Build React app
      run: |
        echo "=== Starting build ==="
        npm run build
        echo "=== Build complete ==="
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
        retention-days: 7
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 7
      if: always()

  # Optional: Deploy to staging on main branch
  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: build/
        
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your deployment commands here
        # Example: aws s3 sync build/ s3://your-staging-bucket/
